# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Government Technology Agency
title-abbreviated: GovTech
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Empowering our nation through technology. From transforming the delivery of Government Digital Services to building Smart Nation Infrastructure, 
  GovTech uses technology to improve the lives of everyone in Singapore.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.tech.gov.sg" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap

# Build settings
markdown: kramdown
remote_theme: isomerpages/isomerpages-template
safe: false

# Breadcrumbs
breadcrumbs:
  root:
    hide: false  # show breadcrumbs on root/home page
    image: false # Show image or title text

collections:
  careers:
    output: true
  who-we-are:
    output: true
  products-and-services:
    output: true

# Resource Room and Pagination
resources_name: "media"
paginate: 12
paginate_path: "/media/page:num"

# Feedback Form URL
feedback_form_url: "https://form.gov.sg/#!/forms/govtech/5bda9d7df5a907000fd1b76e"

# Site configuration for Blueprint
##################################

# Homepage sections
homepage_hero_i_want_to: false # if i_want_to is true, there will be no key highlights
homepage_programmes: true
homepage_resources: true
homepage_careers: false

# Custom CSS file path
custom_css_path: "/do-not-touch/theme-colors/custom.css"
custom_print_css_path: "/assets/css/print.css"

# ############################################################
# # Site configuration for the Jekyll 3 Pagination Gem
# # The values here represent the defaults if nothing is set
# pagination:
  
#   # Site-wide kill switch, disabled here it doesn't run at all 
#   enabled: true

#   # The default document collection to paginate if nothing is specified ('posts' is default)
#   collection: 'posts'

#   # How many objects per paginated page, used to be `paginate` (default: 0, means all)
#   per_page: 12

#   # The permalink structure for the paginated pages (this can be any level deep)
#   permalink: ':num.html' # Pages are index.html inside this folder (default)
#   #permalink: '/page/:num.html' # Pages are simple html files 
#   #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.

#  # Optional,omit or set both before and after to zero to disable. 
#  # Controls how the pagination trail for the paginated pages look like. 
#   trail: 
#     before: 2
#     after: 2

#   # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
#   sort_field: 'date'

#   # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
#   sort_reverse: true

# ############################################################

# autopages:
#   enabled: false

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

exclude: [travis-script.js, .travis.yml, README.md, package.json, package-lock.json, node_modules, vendor/bundle/, vendor/cache/, vendor/gems/, vendor/ruby/, Gemfile, Gemfile.lock]
